### ISSUE TITLE
[ROS Noetic] collada_urdf_jsk_patch failing to build on all platforms

### ISSUE THREAD

**Issue by sloretz** [jsk-ros-pkg/jsk_3rdparty#213]
* http://build.ros.org/job/Nbin_uF64__collada_urdf_jsk_patch__ubuntu_focal_amd64__binary/
* http://build.ros.org/job/Nbin_db_dB64__collada_urdf_jsk_patch__debian_buster_amd64__binary/
* http://build.ros.org/job/Nbin_ufhf_uFhf__collada_urdf_jsk_patch__ubuntu_focal_armhf__binary/
* http://build.ros.org/job/Nbin_ufv8_uFv8__collada_urdf_jsk_patch__ubuntu_focal_arm64__binary/
* http://build.ros.org/job/Nbin_dbv8_dBv8__collada_urdf_jsk_patch__debian_buster_arm64__binary/

It looks like all builds of `collada_urdf_jsk_patch` on ROS Noetic are failing to build.

---

Also, can these patches be applied upstream so that `collada_urdf_jsk_patch` is no longer needed? https://github.com/ros/collada_urdf

**Comment by k-okada** [comment]
thanks , I think this is same as meldoic failrue on 2.1.20 ( https://github.com/ros/rosdistro/pull/26216 ) and will be fixed in 2.1.21 ( https://github.com/ros/rosdistro/pull/26311)

> Also, can these patches be applied upstream so that collada_urdf_jsk_patch is no longer needed?

good question , I really want to  disable this package, and all patches are merged into upstream, but still we have problem on assimp library ( or gazebo ), if we could release newer version of gazebo11 includes  https://github.com/osrf/gazebo/pull/2811, then we could remove jsk_patch package.

Closes #214 and #215 too
